#!/usr/bin/env python3
"""Archive public knowledge pages after Firefox renders their DOM.

This adapter is intentionally separate from the static HTTP archiver.  Each run
creates an empty temporary Firefox profile, connects only to its loopback BiDi
endpoint, and never imports cookies, credentials, extensions, or browser state.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
import shutil
import socket
import subprocess
import tempfile
import time
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urljoin, urlparse

import websockets

from public_knowledge_archive import (
    MAX_PAGES_HARD_LIMIT,
    ArchiveRecord,
    canonicalize,
    filename_for,
    host_allowed,
    is_access_gate,
    is_dynamic_shell,
    load_existing,
    markdown_page,
    robots_allowed,
    safe_output_dir,
)


VISIBLE_SNAPSHOT = """JSON.stringify({
  title: document.title,
  url: location.href,
  text: document.body ? document.body.innerText : '',
  links: Array.from(document.links).map(function(link) { return link.href; }),
  toc: window.appData && window.appData.book && Array.isArray(window.appData.book.toc)
    ? window.appData.book.toc : []
})"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Bounded public-only archive using a temporary Firefox renderer.")
    parser.add_argument("--source", action="append", help="Public seed URL. Repeat for multiple knowledge bases.")
    parser.add_argument("--source-manifest", action="append", help="Local JSON manifest with a urls array generated by this tool.")
    parser.add_argument("--manifest-out", help="Local discovery manifest path; defaults to <output-dir>/rendered-discovery.json.")
    parser.add_argument("--allow-domain", action="append", required=True, help="Allowed public domain. Repeat as needed.")
    parser.add_argument("--output-dir", required=True, help="Archive output directory outside Codex source/runtime paths.")
    parser.add_argument("--category", default="public-knowledge", help="Local archive classification label.")
    parser.add_argument("--max-pages", type=int, default=20, help="Maximum pages for this run (1-100).")
    parser.add_argument("--max-depth", type=int, default=1, help="Link depth from seed URLs (0-2).")
    parser.add_argument("--refresh", action="store_true", help="Store a body even if its content hash is unchanged.")
    parser.add_argument("--dry-run", action="store_true", help="Render and discover pages without writing archive files.")
    parser.add_argument("--timeout", type=int, default=20, help="Per-navigation and robots timeout in seconds.")
    parser.add_argument("--render-wait", type=float, default=5.0, help="Maximum bounded wait for rendered text or toc (0-10 seconds).")
    parser.add_argument("--firefox-bin", default="firefox", help="Firefox executable; must be a local browser binary.")
    return parser.parse_args()


def free_loopback_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as listener:
        listener.bind(("127.0.0.1", 0))
        return int(listener.getsockname()[1])


def toc_urls(nodes: Any) -> list[str]:
    """Return public document route fragments from Yuque's rendered book tree."""
    result: list[str] = []
    if isinstance(nodes, list):
        for node in nodes:
            result.extend(toc_urls(node))
    elif isinstance(nodes, dict):
        route = nodes.get("url")
        if isinstance(route, str) and route.strip():
            result.append(route.strip())
        for value in nodes.values():
            if isinstance(value, (dict, list)):
                result.extend(toc_urls(value))
    return result


def resolve_child(base_url: str, href: str, from_toc: bool) -> str:
    """Resolve normal links normally and Yuque toc route fragments under the book root."""
    if from_toc and not urlparse(href).scheme and not href.startswith("/"):
        return canonicalize(f"{base_url.rstrip('/')}/{href}")
    return canonicalize(urljoin(base_url, href))


def manifest_urls(paths: list[str] | None) -> list[str]:
    urls: list[str] = []
    for value in paths or []:
        data = json.loads(Path(value).read_text(encoding="utf-8"))
        listed = data.get("urls")
        if not isinstance(listed, list) or not all(isinstance(url, str) for url in listed):
            raise ValueError(f"invalid source manifest: {value}")
        urls.extend(listed)
    return urls


def is_not_found(title: str, text: str) -> bool:
    marker = (title + "\n" + text[:400]).lower()
    return "404" in marker and "not found" in marker


def book_root(url: str) -> str | None:
    parsed = urlparse(url)
    parts = [part for part in parsed.path.split("/") if part]
    if len(parts) < 3:
        return None
    return canonicalize(f"{parsed.scheme}://{parsed.netloc}/{parts[0]}/{parts[1]}")


class FirefoxBidiRenderer:
    def __init__(self, firefox_bin: str, timeout: int, render_wait: float) -> None:
        self.firefox_bin = firefox_bin
        self.timeout = timeout
        self.render_wait = render_wait
        self._profile: tempfile.TemporaryDirectory[str] | None = None
        self._process: subprocess.Popen[bytes] | None = None
        self._websocket: Any | None = None
        self._loop: asyncio.AbstractEventLoop | None = None
        self._next_id = 1
        self._context: str | None = None

    def __enter__(self) -> "FirefoxBidiRenderer":
        if os.environ.get("CODEX_OFFLINE_HERMETIC") == "1":
            raise RuntimeError("network disabled by CODEX_OFFLINE_HERMETIC")
        executable = shutil.which(self.firefox_bin)
        if not executable:
            raise RuntimeError(f"renderer-unavailable: Firefox executable not found: {self.firefox_bin}")
        self._profile = tempfile.TemporaryDirectory(prefix="codex-public-render-")
        port = free_loopback_port()
        self._process = subprocess.Popen(
            [executable, "--headless", "--profile", self._profile.name, "--remote-debugging-port", str(port), "about:blank"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        self._loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._connect(f"ws://127.0.0.1:{port}/session"))
        return self

    def __exit__(self, _exc_type: object, _exc: object, _traceback: object) -> None:
        try:
            if self._loop is not None:
                self._loop.run_until_complete(self._close())
        finally:
            if self._process is not None and self._process.poll() is None:
                self._process.terminate()
                try:
                    self._process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    self._process.kill()
                    self._process.wait(timeout=5)
            if self._profile is not None:
                self._profile.cleanup()
            if self._loop is not None:
                self._loop.close()

    async def _connect(self, endpoint: str) -> None:
        deadline = time.monotonic() + self.timeout
        while True:
            try:
                self._websocket = await websockets.connect(endpoint, open_timeout=2)
                break
            except OSError:
                if time.monotonic() >= deadline:
                    raise RuntimeError("renderer-unavailable: Firefox BiDi endpoint did not become ready")
                await asyncio.sleep(0.2)
        await self._call("session.new", {"capabilities": {}})
        tree = await self._call("browsingContext.getTree", {})
        contexts = tree["contexts"]
        if not contexts:
            raise RuntimeError("renderer-unavailable: Firefox has no top-level browsing context")
        self._context = str(contexts[0]["context"])

    async def _close(self) -> None:
        if self._websocket is None:
            return
        try:
            await self._call("session.end", {})
        except Exception:
            pass
        await self._websocket.close()

    async def _call(self, method: str, params: dict[str, Any]) -> dict[str, Any]:
        if self._websocket is None:
            raise RuntimeError("renderer-unavailable: BiDi connection is not open")
        request_id = self._next_id
        self._next_id += 1
        try:
            await self._websocket.send(json.dumps({"id": request_id, "method": method, "params": params}))
            while True:
                raw = await asyncio.wait_for(self._websocket.recv(), timeout=self.timeout)
                response = json.loads(raw)
                if response.get("id") != request_id:
                    continue
                if response.get("type") != "success":
                    raise RuntimeError(f"renderer-error: {method}: {response.get('error', response)}")
                return response["result"]
        except asyncio.TimeoutError as exc:
            raise RuntimeError(f"renderer-error: {method}: timed out after {self.timeout}s") from exc

    async def _render(self, url: str, allow_toc_ready: bool) -> dict[str, Any]:
        if self._context is None:
            raise RuntimeError("renderer-unavailable: missing browsing context")
        before = await self._snapshot()
        before_url = canonicalize(str(before.get("url", "")))
        target_url = canonicalize(url)
        await self._call("browsingContext.navigate", {"context": self._context, "url": url, "wait": "none"})
        deadline = time.monotonic() + self.render_wait
        while True:
            latest = await self._snapshot()
            current_url = canonicalize(str(latest.get("url", "")))
            moved_from_previous = target_url == before_url or current_url != before_url
            toc_ready = allow_toc_ready and bool(latest["toc"])
            if moved_from_previous and (len(latest["text"].strip()) >= 200 or toc_ready or time.monotonic() >= deadline):
                return latest
            await asyncio.sleep(0.5)

    async def _snapshot(self) -> dict[str, Any]:
        if self._context is None:
            raise RuntimeError("renderer-unavailable: missing browsing context")
        result = await self._call(
            "script.evaluate",
            {
                "expression": VISIBLE_SNAPSHOT,
                "target": {"context": self._context},
                "awaitPromise": True,
                "resultOwnership": "none",
            },
        )
        remote = result.get("result", {})
        if result.get("type") != "success" or remote.get("type") != "string":
            raise RuntimeError("renderer-error: document snapshot was not a JSON string")
        snapshot = json.loads(remote["value"])
        if not isinstance(snapshot.get("text"), str) or not isinstance(snapshot.get("links"), list) or not isinstance(snapshot.get("toc"), list):
            raise RuntimeError("renderer-error: malformed document snapshot")
        return snapshot

    def render(self, url: str, allow_toc_ready: bool = False) -> dict[str, Any]:
        if self._loop is None:
            raise RuntimeError("renderer-unavailable: event loop is not open")
        return self._loop.run_until_complete(self._render(url, allow_toc_ready))


def main() -> int:
    args = parse_args()
    if not 1 <= args.max_pages <= MAX_PAGES_HARD_LIMIT:
        raise SystemExit(f"--max-pages must be 1-{MAX_PAGES_HARD_LIMIT}")
    if not 0 <= args.max_depth <= 2:
        raise SystemExit("--max-depth must be 0-2")
    if not 0 <= args.render_wait <= 10:
        raise SystemExit("--render-wait must be 0-10")
    allow_domains = tuple(sorted({value.strip().lower() for value in args.allow_domain if value.strip()}))
    direct_seeds = [canonicalize(url) for url in args.source or []]
    manifest_seeds = [canonicalize(url) for url in manifest_urls(args.source_manifest)]
    seeds = [*direct_seeds, *manifest_seeds]
    if not seeds:
        raise SystemExit("at least one --source or --source-manifest is required")
    for seed in seeds:
        if urlparse(seed).scheme not in {"http", "https"} or not host_allowed(seed, allow_domains):
            raise SystemExit(f"source is outside the explicit public allowlist: {seed}")

    output_dir = safe_output_dir(args.output_dir)
    existing = load_existing(output_dir / "index.jsonl")
    queue: list[tuple[str, int]] = [(seed, 0) for seed in direct_seeds]
    queue.extend((seed, 0) for seed in manifest_seeds if seed not in existing)
    seen: set[str] = set()
    records: list[ArchiveRecord] = []
    robots_cache: dict[str, bool] = {}
    discovered_urls: set[str] = set(manifest_seeds)
    primed_books: set[str] = set()

    try:
        with FirefoxBidiRenderer(args.firefox_bin, args.timeout, args.render_wait) as renderer:
            while queue and len(records) < args.max_pages:
                requested, depth = queue.pop(0)
                canonical = canonicalize(requested)
                if canonical in seen:
                    continue
                seen.add(canonical)
                now = datetime.now(timezone.utc).isoformat()
                if not host_allowed(canonical, allow_domains):
                    records.append(ArchiveRecord(canonical, canonical, "", now, "", 0, args.category, depth, "blocked-domain", None, "outside allowlist"))
                    continue
                if not robots_allowed(canonical, args.timeout, robots_cache):
                    records.append(ArchiveRecord(canonical, canonical, "", now, "", 0, args.category, depth, "blocked-robots", None, "robots unavailable or disallowed"))
                    continue
                try:
                    parent_book = book_root(canonical)
                    if parent_book and parent_book not in primed_books:
                        renderer.render(parent_book, allow_toc_ready=True)
                        primed_books.add(parent_book)
                    snapshot = renderer.render(canonical, allow_toc_ready=(depth == 0))
                except RuntimeError as exc:
                    records.append(ArchiveRecord(canonical, canonical, "", now, "", 0, args.category, depth, "render-error", None, str(exc)))
                    continue
                final_url = canonicalize(str(snapshot.get("url", canonical)))
                if not host_allowed(final_url, allow_domains):
                    records.append(ArchiveRecord(canonical, final_url, "", now, "", 0, args.category, depth, "blocked-redirect", None, "redirected outside allowlist"))
                    continue
                title = " ".join(str(snapshot.get("title", "")).split()) or "Untitled public page"
                text = "\n".join(line.strip() for line in str(snapshot["text"]).splitlines() if line.strip()).strip()
                children: list[str] = []
                if depth < args.max_depth:
                    for href in snapshot["links"]:
                        child = resolve_child(final_url, str(href), from_toc=False)
                        if urlparse(child).scheme in {"http", "https"} and host_allowed(child, allow_domains):
                            children.append(child)
                    for href in toc_urls(snapshot["toc"]):
                        child = resolve_child(final_url, href, from_toc=True)
                        if urlparse(child).scheme in {"http", "https"} and host_allowed(child, allow_domains):
                            children.append(child)
                if is_access_gate(final_url, text):
                    records.append(ArchiveRecord(canonical, final_url, title, now, "", len(text), args.category, depth, "access-gated", None, "login or verification page"))
                    continue
                if is_not_found(title, text):
                    records.append(ArchiveRecord(canonical, final_url, title, now, "", len(text), args.category, depth, "not-found", None, "public page reports 404"))
                    continue
                if is_dynamic_shell(text):
                    if children:
                        discovered_urls.update(children)
                        records.append(ArchiveRecord(canonical, final_url, title, now, "", len(text), args.category, depth, "rendered-index", None, "rendered directory with allowed child links"))
                        queue.extend((child, depth + 1) for child in children)
                        continue
                    records.append(ArchiveRecord(canonical, final_url, title, now, "", len(text), args.category, depth, "dynamic-shell", None, "insufficient rendered visible text"))
                    continue
                digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
                relative = f"pages/{filename_for(final_url)}"
                state = "unchanged" if existing.get(canonical) == digest and not args.refresh else "archived"
                record = ArchiveRecord(canonical, final_url, title, now, digest, len(text), args.category, depth, state, relative, "renderer=firefox-bidi")
                records.append(record)
                if not args.dry_run and state == "archived":
                    (output_dir / "pages").mkdir(parents=True, exist_ok=True)
                    (output_dir / relative).write_text(markdown_page(record, text), encoding="utf-8")
                queue.extend((child, depth + 1) for child in children)
                discovered_urls.update(children)
    except RuntimeError as exc:
        now = datetime.now(timezone.utc).isoformat()
        records.append(ArchiveRecord("", "", "", now, "", 0, args.category, 0, "renderer-unavailable", None, str(exc)))

    if not args.dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)
        manifest_path = Path(args.manifest_out).expanduser().resolve() if args.manifest_out else output_dir / "rendered-discovery.json"
        manifest_path.write_text(json.dumps({"kind": "rendered-public-knowledge-discovery", "urls": sorted(discovered_urls)}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        with (output_dir / "index.jsonl").open("a", encoding="utf-8") as handle:
            for record in records:
                handle.write(json.dumps(asdict(record), ensure_ascii=False, sort_keys=True) + "\n")
        run = {
            "kind": "rendered-public-knowledge-archive-run",
            "renderer": "firefox-bidi-temporary-profile",
            "retrieved_at": datetime.now(timezone.utc).isoformat(),
            "allow_domains": allow_domains,
            "sources": seeds,
            "max_pages": args.max_pages,
            "max_depth": args.max_depth,
            "records": [asdict(record) for record in records],
            "raw_content_stored": False,
        }
        (output_dir / "latest-rendered-run.json").write_text(json.dumps(run, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": "dry-run" if args.dry_run else "ok", "records": [asdict(record) for record in records]}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
